# Generated by Django 5.0.4 on 2024-04-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('price', models.CharField(choices=[('', 'Choose your price*'), ('1000 - 3000 USD', '1000 - 3000 USD'), ('3000 - 6000 USD', '3000 - 6000 USD'), ('6000 - 10,000 USD', '6000 - 10,000 USD'), ('Over 10,000 USD', 'Over 10,000 USD')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home Page - Inquiry',
                'verbose_name_plural': 'Home Page - Inquiries',
            },
        ),
    ]
