# Generated by Django 5.0.4 on 2024-04-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_inquiry_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryAntaraCares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('price', models.CharField(choices=[('', 'Choose your price*'), ('1000 - 3000 USD', '1000 - 3000 USD'), ('3000 - 6000 USD', '3000 - 6000 USD'), ('6000 - 10,000 USD', '6000 - 10,000 USD'), ('Over 10,000 USD', 'Over 10,000 USD')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Antara Cares - Inquiry',
                'verbose_name_plural': 'Antara Cares - Inquiries',
            },
        ),
        migrations.CreateModel(
            name='InquiryBrandIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('price', models.CharField(choices=[('', 'Choose your price*'), ('1000 - 3000 USD', '1000 - 3000 USD'), ('3000 - 6000 USD', '3000 - 6000 USD'), ('6000 - 10,000 USD', '6000 - 10,000 USD'), ('Over 10,000 USD', 'Over 10,000 USD')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brand Identity - Inquiry',
                'verbose_name_plural': 'Brand Identity - Inquiries',
            },
        ),
        migrations.CreateModel(
            name='InquiryEdubestOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('price', models.CharField(choices=[('', 'Choose your price*'), ('1000 - 3000 USD', '1000 - 3000 USD'), ('3000 - 6000 USD', '3000 - 6000 USD'), ('6000 - 10,000 USD', '6000 - 10,000 USD'), ('Over 10,000 USD', 'Over 10,000 USD')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Edubest Online - Inquiry',
                'verbose_name_plural': 'Edubest Online - Inquiries',
            },
        ),
        migrations.CreateModel(
            name='InquiryEnhance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('price', models.CharField(choices=[('', 'Choose your price*'), ('1000 - 3000 USD', '1000 - 3000 USD'), ('3000 - 6000 USD', '3000 - 6000 USD'), ('6000 - 10,000 USD', '6000 - 10,000 USD'), ('Over 10,000 USD', 'Over 10,000 USD')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enhance - Inquiry',
                'verbose_name_plural': 'Enhance - Inquiries',
            },
        ),
        migrations.CreateModel(
            name='InquiryEvasionExotique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('price', models.CharField(choices=[('', 'Choose your price*'), ('1000 - 3000 USD', '1000 - 3000 USD'), ('3000 - 6000 USD', '3000 - 6000 USD'), ('6000 - 10,000 USD', '6000 - 10,000 USD'), ('Over 10,000 USD', 'Over 10,000 USD')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evasion Exotique - Inquiry',
                'verbose_name_plural': 'Evasion Exotique - Inquiries',
            },
        ),
        migrations.CreateModel(
            name='InquiryI2C2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('price', models.CharField(choices=[('', 'Choose your price*'), ('1000 - 3000 USD', '1000 - 3000 USD'), ('3000 - 6000 USD', '3000 - 6000 USD'), ('6000 - 10,000 USD', '6000 - 10,000 USD'), ('Over 10,000 USD', 'Over 10,000 USD')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'I2C2 - Inquiry',
                'verbose_name_plural': 'I2C2 - Inquiries',
            },
        ),
        migrations.CreateModel(
            name='InquiryIconicCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('price', models.CharField(choices=[('', 'Choose your price*'), ('1000 - 3000 USD', '1000 - 3000 USD'), ('3000 - 6000 USD', '3000 - 6000 USD'), ('6000 - 10,000 USD', '6000 - 10,000 USD'), ('Over 10,000 USD', 'Over 10,000 USD')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Iconic City - Inquiry',
                'verbose_name_plural': 'Iconic City - Inquiries',
            },
        ),
        migrations.CreateModel(
            name='InquiryWebsiteDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('price', models.CharField(choices=[('', 'Choose your price*'), ('1000 - 3000 USD', '1000 - 3000 USD'), ('3000 - 6000 USD', '3000 - 6000 USD'), ('6000 - 10,000 USD', '6000 - 10,000 USD'), ('Over 10,000 USD', 'Over 10,000 USD')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Website Design - Inquiry',
                'verbose_name_plural': 'Website Design - Inquiries',
            },
        ),
    ]
